spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: true
  datasource:
    url: jdbc:mysql://localhost:3306/perf?socketTimeout=5000&connectTimeout=3000
    # socketTimeout: Maximum time (ms) to wait for a response after sending the query
    # connectTimeout: Maximum time (ms) to establish a connection to the DB server
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    org:
      hibernate:
        SQL: off
        type: off


multi-tenant:
  enabled : false
  default-data-source: perf
  entity-packages:
      - com.syscho.multi
  datasources:
    default:
      url: jdbc:mysql://localhost:3306/dev
      username: root
      password: root
    dev:
      url: jdbc:mysql://localhost:3306/dev
      username: root
      password: root
    perf:
      url: jdbc:mysql://localhost:3306/perf
      username: root
      password: root



